<?php

namespace AppBundle\Repository;

/**
 * CauseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CauseRepository extends \Doctrine\ORM\EntityRepository
{
}
